### ISSUE TITLE
Add possibility to check and download update for app

### ISSUE THREAD

**Issue by michalkurpis** [kleder/timetracker#38] opened 2018-02-02 15:33 UTC
## Expected Behavior
Add possibility to check and update app, e.g. Nuts

## Actual Behavior
Not possible to auto-update app's version

## Specifications

  - T-REC Version: 1.1.0
  - Platform: (mac/linux/windows): all

**Comment by rkorszun** [comment] 2018-02-03 10:45
This is duplicate of #28

**Closed as completed** 2018-02-05 06:23 UTC
Labels: feature request
